name: OnlineUI
version: 3.0.0
main: Kylan1940\OnlineUI\Main
api: 5.0.0
author: Kylan1940

commands:
  online:
    description: "Check online players with UI"
    permission: "onlineui.command"
    
permissions:
  onlineui.command:
    description: "Permission for OnlineUI command"
    default: yes
