# ===========================================================================
# ╭━━━╮╱╱╭╮╱╱╱╱╱╱╱╭╮╱╭┳━━╮
# ┃╭━╮┃╱╱┃┃╱╱╱╱╱╱╱┃┃╱┃┣┫┣╯
# ┃┃╱┃┣━╮┃┃╭┳━╮╭━━┫┃╱┃┃┃┃
# ┃┃╱┃┃╭╮┫┃┣┫╭╮┫┃━┫┃╱┃┃┃┃
# ┃╰━╯┃┃┃┃╰┫┃┃┃┃┃━┫╰━╯┣┫┣╮
# ╰━━━┻╯╰┻━┻┻╯╰┻━━┻━━━┻━━╯
# ===========================================================================
# Report Plugin: https://github.com/Kylan1940/OnlineUI/issues/new
# ===========================================================================
# Github: https://github.com/Kylan1940
# Website: https://web.kylan1940.online
# ===========================================================================

# ONLINEUI CONFIGURATION
#
# HELP:
# \n for new line
# § for color and special symbols

# Config Version
# DON'T CHANGE THIS!!! 
config-version: "2" 

# Command:
only-ingame: "This command is only in game!"

# UI
title: "§aOnline§7UI"
content: "Players Online: "